apiVersion: v1
kind: Service
metadata:
  name: labapp
spec:
  selector:
    app: labapp                     # 把流量转给带这个标签的 Pod
  ports:
    - port: 80                      # Service 自己的端口
      targetPort: 8000              # Pod 的端口
